src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>9</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>submits the expense for approval</description>
        <label>Submitted</label>
        <type>Checkbox</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExpensesSubmitterBatchTest.cls
/**
 *
 */
@isTest
public class ExpensesSubmitterBatchTest {

    /**
    * Creates a couple of expenses with amount greater than 5000 and submitted = false.
    */
	@testSetup static void setup(){
	    TestUtils.createRandomExpenses();
	}
	
	/**
	 * Checks all expenses created in the setup method was submitted
	 */
    @isTest static void executeBatchTest() {
        Test.startTest();
        ExpensesSubmitterBatch batch = new ExpensesSubmitterBatch();
        Id batchId = Database.executeBatch(batch);
        Test.stopTest();

        // after the testing stops, assert records were updated properly
        System.assertEquals(0, [select count() from Expense__c where Submitted__c = false and Amount__c > 5000], 'At least one expense with amount greater than 5000 was not submitted');
    }
}