src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>9</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Select the nature of your expense</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cell Phone &amp; Internet Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Road Meals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printing &amp; Copying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lodging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Development Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Company__c</fullName>
        <label>Client Company</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expense_Status__c</fullName>
        <label>Expense Status</label>
        <picklist>
            <picklistValues>
                <fullName>NOT SUBMITTED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SUBMITTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPROVED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REJECTED</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>submits the expense for approval</description>
        <label>Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Travel_country__c</fullName>
        <label>Travel country</label>
        <picklist>
            <controllingField>Travel_region__c</controllingField>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mexico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Venezuela</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indonesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vietnam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Travel_region__c</fullName>
        <label>Travel region</label>
        <picklist>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Business trips</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client meetings</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUtils.cls
public class TestUtils {

    public static void createRandomExpenses(){
        createRandomExpenses(40);
        createRandomExpensesWithAmountGreaterThan5000(40);
    }
        
    /**
    * 
    */
    private static void createRandomExpenses(integer cant) {
        List<Expense__c> expenses = new List<Expense__c>();
		for(integer i=0; i<cant; i++){
			Expense__c expense = new Expense__c();
			expense.Name = 'expense'+1;
			
			Contact employee = new Contact();
			employee.LastName = 'Test'+i;
			insert employee; 
			
			expense.Employee__c = employee.Id;
			
			//just for generating expenses with different business trips and clients meetings types
			if(math.mod(i, 2) == 0){
				expense.Type__c = 'Business trips';
				expense.Travel_country__c = 'India';
				expense.Travel_region__c = 'Asia';
			}else{
				expense.Type__c = 'Client meetings';
				
			}
			expense.Amount__c = 1000*1; 
			expense.Category__c = 'Transportation';
			expense.Client_Company__c = 'Company'+1;
			
			if(getRandomBoolean()){
				expense.Submitted__c = false;
				expense.Expense_Status__c = 'NOT SUBMITTED';
			}else{
				expense.Submitted__c = true;
				expense.Expense_Status__c = 'SUBMITTED';
			}
			
			expenses.add(expense);
		}
		insert expenses;
    }
    
    /**
    * 
    */
    private static void createRandomExpensesWithAmountGreaterThan5000(integer cant){
        List<Expense__c> expenses = new List<Expense__c>();
		for(integer i=0; i<cant; i++){
		    Expense__c expense = new Expense__c();
			expense.Name = 'expense'+1;
			
			Contact employee = new Contact();
			employee.LastName = 'Test'+i;
			insert employee; 
			
			expense.Employee__c = employee.Id;
			expense.Type__c = 'Client meetings';
			expense.Submitted__c = false;
			expense.Expense_Status__c = 'NOT SUBMITTED';
			expense.Amount__c = 6000;
			expense.Category__c = 'Transportation';
			expense.Client_Company__c = 'Company'+1;
			
			expenses.add(expense);
		}
		insert expenses;
    }
    
    public static Boolean getRandomBoolean(){
         return math.mod(getRandomNumber(10),2) == 0;
    }
    
    public static Integer getRandomNumber(Integer size){
          Double d = math.random() * size;
          return d.intValue();
     }
     
    /**
	 * Returns the first contact in the database 
	 */
	public static Contact getAContact(){
		List<Contact> employees = [select Id from Contact limit 1];
    	System.assert(employees != null);
    	System.assert(!employees.isempty());
    	return  employees.get(0);
	}
}