src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>9</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>submits the expense for approval</description>
        <label>Submitted</label>
        <type>Checkbox</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExpensesSubmitterBatch.cls
/**
* Batch for submitting all the expenses with the amount greater that 5000
*/
global class ExpensesSubmitterBatch implements Database.Batchable<sObject> {

    global Iterable<sObject> start(Database.BatchableContext bc) {
        //get the batch records to be processed in the execute method
        return [select Id from Expense__c where Submitted__c = false and Amount__c > 5000];
    }

    global void execute(Database.BatchableContext bc, List<Expense__c> records){
        //set the submitted flag of the expense to true and update the records in the database
        for(Expense__c expense :records){
            expense.Submitted__c = true;
        }
        update records;
    }    

    global void finish(Database.BatchableContext bc){
        // TODO send an email
    }    

}